name: test
on:
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reshnm/ocm-action@main
        with:
          ocm-version: "latest"
          base-url: "ghcr.io/reshnm/test"
          components-definition-path: "components.yaml"
          version: "1.1.1"
      - run: |
          echo "Hello, world!"